# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AdminBundle\Entity\UserRemidio:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
    
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:        
        admin:
            entity:
                class: AdminBundle:UserRemidio
                property: username
#            id: AdminBundle\Security\User\AdminUserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        api:
            pattern: ^/api
            security: false
        
        admin_area:
            
            pattern:      ^/
            anonymous: ~
            form_login:
                provider:       admin
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
                always_use_default_target_path: false
                default_target_path:  /index
            logout:
                path:           /logout
                target:         /login

#            remember_me:
#                secret:      "%secret%"
#                lifetime: 3600
#                path:     /
#            anonymous:    true

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            
    access_control:
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: [ROLE_ADMIN] }
