<?php

namespace AdminBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRemidioRepository extends \Doctrine\ORM\EntityRepository
{
   
}
